- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-081c885356ebfe00e # replace with your SG ID
    zone_id: "Z009120826G54L5D7TCYM"
    domain_name: "daws86b.fun"
    instance:
    - mongodb
    - redis
    - mysql
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      Name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"      
    loop: "{{ instance }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg:"{{ ec2_output }}"