- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-081c885356ebfe00e
    zone_id: "Z009120826G54L5D7TCYM"
    domain_name: "daws86b.fun"
    instance:
      - mongodb

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        image_id: "{{ ami_id }}"
        security_group_id:
          - "{{ sg_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instance }}"
      register: ec2_output

    - name: print the ec2_output
      ansible.builtin.debug:
        var: ec2_output
